export const allCalendarData = {
  dates: [
    {
      number: 28,
      day: "28.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 29,
      day: "29.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 30,
      day: "30.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 31,
      day: "31.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 1,
      day: "01.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 2,
      day: "02.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 3,
      day: "03.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 4,
      day: "04.09.2023",
      events: { type: "Сегодняшний день", firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 5,
      day: "05.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 6,
      day: "06.09.2023",
      events: { type: "Личная встреча", firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 7,
      day: "07.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 8,
      day: "08.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: true,
      },
      disabled: false,
    },
    {
      number: 9,
      day: "09.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 10,
      day: "10.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 11,
      day: "11.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 12,
      day: "12.09.2023",
      events: {
        type: "Зарубежное мероприятие Фонда Росконгресс ",
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 13,
      day: "13.09.2023",
      events: {
        type: "Зарубежное мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: true,
      },
      disabled: false,
    },
    {
      number: 14,
      day: "14.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 15,
      day: "15.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 16,
      day: "16.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 17,
      day: "17.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 18,
      day: "18.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 19,
      day: "19.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 20,
      day: "20.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 21,
      day: "21.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 22,
      day: "22.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 23,
      day: "23.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 24,
      day: "24.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 25,
      day: "25.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 26,
      day: "26.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 27,
      day: "27.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: true,
      },
      disabled: false,
    },
    {
      number: 28,
      day: "28.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 29,
      day: "29.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 30,
      day: "30.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 1,
      day: "01.10.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
  ],
  daysName: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
  legend: [
    "Сегодняшний день",
    "Личная встреча",
    "Российское мероприятие Фонда Росконгресс ",
    "Зарубежное мероприятие Фонда Росконгресс ",
  ],
};

export const calendarEventsData = [
  {
    id: 1,
    date: {
      gtm: "GTM+3",
      firstNumber: "6",
      secondNumber: "",
      month: "Сент",
      id: 1,
    },
    card: {
      type: "Встреча",
      title: "Бизнес-встреча",
      subtitle:
        "Встреча бизнес-парнтеров и единомышленников в сфере нетворкинга",
      isMember: true,
      isForum: false,
      start: "Начало: 13:30 по мск",
      location: "Биржа деловых контактов",
      telNumber: "",
      site: "",
      user: { name: "Анатолий Чемезов", avatar: "/imgSecond/Avatar.png" },
    },
  },
  {
    id: 2,
    date: {
      gtm: "GTM+3",
      firstNumber: "7",
      secondNumber: "8",
      month: "Сент",
      id: 1,
    },
    card: {
      type: "Российское мероприятие",
      title: "Российская энергетическая неделя",
      subtitle:
        "Международный форум «Российская энергетическая неделя» является одной из ключевых международных площадок для обсуждения актуальных тенденций развития современного топливно-энергетического комплекса. Мероприятие традиционно проходит на самом высоком уровне с участием руководителей крупнейших компаний энергетической отрасли. Организаторами Форума являются Фонд Росконгресс, Министерство энергетики Российской Федерации при поддержке Правительства Москвы.",
      isMember: false,
      isForum: true,
      start: "",
      location: "Москва, Россия",
      telNumber: "+7 (495) 640 5844",
      site: "info@rusenergyweek.com",
      user: { name: "", avatar: "" },
    },
  },
  {
    id: 3,
    date: {
      gtm: "GTM+3",
      firstNumber: "12",
      secondNumber: "13",
      month: "Сент",
      id: 1,
    },
    card: {
      type: "Зарубежное мероприятие",
      title: "XI Международный Форум «Антиконтрафакт - 2023»",
      subtitle:
        "Форум является главной дискуссионной площадкой Евразийского Экономического Союза, на которой представители органов власти и бизнеса обсуждают вопросы защиты рынка от контрафакта и фальсификата, правового регулирования в сфере стандартизации и сертификации, а также защиты прав интеллектуальной собственности.",
      isMember: false,
      isForum: true,
      start: "",
      location: "Санкт-Петербург, Россия",
      telNumber: "+7 (812) 406 7472",
      site: "www.antikontrafact-forum.ru",
      user: { name: "", avatar: "" },
    },
  },
  {
    id: 4,
    date: {
      gtm: "GTM+3",
      firstNumber: "24",
      secondNumber: "27",
      month: "Сент",
      id: 1,
    },
    card: {
      type: "Российское мероприятие",
      title: "Форум «Азартные игры: отчисления на спорт»",
      subtitle:
        "Форум является основной площадкой для взаимодействия федеральных органов законодательной и исполнительной власти, организаторов азартных игр, общероссийских спортивных федераций и профессиональных спортивных лиг.",
      isMember: true,
      isForum: true,
      start: "",
      location: "Москва, Россия",
      telNumber: "+7 (495) 640 4440",
      site: "forumais.ru",
      user: { name: "", avatar: "" },
    },
  },
];

export const myEventsCalendarData = {
  dates: [
    {
      number: 28,
      day: "28.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 29,
      day: "29.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 30,
      day: "30.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 31,
      day: "31.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 1,
      day: "01.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 2,
      day: "02.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 3,
      day: "03.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 4,
      day: "04.09.2023",
      events: { type: "Сегодняшний день", firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 5,
      day: "05.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 6,
      day: "06.09.2023",
      events: { type: "Личная встреча", firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 7,
      day: "07.09.2023",
      events: {
        type: null,
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 8,
      day: "08.09.2023",
      events: {
        type: null,
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 9,
      day: "09.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 10,
      day: "10.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 11,
      day: "11.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 12,
      day: "12.09.2023",
      events: {
        type: null,
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 13,
      day: "13.09.2023",
      events: {
        type: null,
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 14,
      day: "14.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 15,
      day: "15.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 16,
      day: "16.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 17,
      day: "17.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 18,
      day: "18.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 19,
      day: "19.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 20,
      day: "20.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 21,
      day: "21.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 22,
      day: "22.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 23,
      day: "23.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 24,
      day: "24.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 25,
      day: "25.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 26,
      day: "26.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 27,
      day: "27.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: true,
      },
      disabled: false,
    },
    {
      number: 28,
      day: "28.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 29,
      day: "29.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 30,
      day: "30.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 1,
      day: "01.10.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
  ],
  daysName: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
  legend: [
    "Сегодняшний день",
    "Личная встреча",
    "Российское мероприятие Фонда Росконгресс ",
    "Зарубежное мероприятие Фонда Росконгресс ",
  ],
};

export const forumEventsCalendarData = {
  dates: [
    {
      number: 28,
      day: "28.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 29,
      day: "29.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 30,
      day: "30.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 31,
      day: "31.08.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
    {
      number: 1,
      day: "01.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 2,
      day: "02.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 3,
      day: "03.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 4,
      day: "04.09.2023",
      events: { type: "Сегодняшний день", firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 5,
      day: "05.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 6,
      day: "06.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 7,
      day: "07.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 8,
      day: "08.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: true,
      },
      disabled: false,
    },
    {
      number: 9,
      day: "09.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 10,
      day: "10.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 11,
      day: "11.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 12,
      day: "12.09.2023",
      events: {
        type: "Зарубежное мероприятие Фонда Росконгресс ",
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 13,
      day: "13.09.2023",
      events: {
        type: "Зарубежное мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: true,
      },
      disabled: false,
    },
    {
      number: 14,
      day: "14.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 15,
      day: "15.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 16,
      day: "16.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 17,
      day: "17.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 18,
      day: "18.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 19,
      day: "19.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 20,
      day: "20.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 21,
      day: "21.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 22,
      day: "22.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 23,
      day: "23.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: true,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 24,
      day: "24.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 25,
      day: "25.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 26,
      day: "26.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: false,
      },
      disabled: false,
    },
    {
      number: 27,
      day: "27.09.2023",
      events: {
        type: "Российское мероприятие Фонда Росконгресс ",
        firstDay: false,
        lastDay: true,
      },
      disabled: false,
    },
    {
      number: 28,
      day: "28.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 29,
      day: "29.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 30,
      day: "30.09.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: false,
    },
    {
      number: 1,
      day: "01.10.2023",
      events: { type: null, firstDay: false, lastDay: false },
      disabled: true,
    },
  ],
  daysName: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
  legend: [
    "Сегодняшний день",
    "Личная встреча",
    "Российское мероприятие Фонда Росконгресс ",
    "Зарубежное мероприятие Фонда Росконгресс ",
  ],
};
